name: push_workflow
on: [push]
jobs:
  check-django-version:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository
      - uses: actions/checkout@v3

      # 2. Set up Python environment
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # 원하는 Python 버전을 입력하세요 (예: '3.9')
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 4. Check Django version
      - name: Check Django version
        run: |
          python -m django --version

      # 5. Run Django system check
      - name: Django System Check
        run: |
          python manage.py check

      # 6. Run Django tests (optional: if you have tests set up)
      - name: Run Django Tests
        run: |
          python manage.py test