name: push_workflow
on: [push]
jobs:
  check-django-version:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository
      - uses: actions/checkout@v3

      # 2. Set up Python environment
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # 원하는 Python 버전을 명시하세요

      # 3. Install system dependencies (for Pillow and other packages)
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libjpeg-dev zlib1g-dev libmysqlclient-dev

      # 4. Upgrade pip
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # 5. Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # 6. Check Django version
      - name: Check Django version
        run: python -m django --version

      # 7. Run Django system check
      - name: Django System Check
        run: python manage.py check